### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by SnoopyDevelops** [avi1245/Heart-Rate-Detection#1]
![image](https://user-images.githubusercontent.com/54778084/106839650-9e9da500-66d9-11eb-9d8e-8a0e3c13d983.png)

**Comment by WillLiGitHub** [comment]
same error, anyone had a sulotion!

**Comment by allComputableThings** [comment]
Looks like "ws.receive()" is returning None.

Also tried running with Flask as the server:

```
%python app.py 
...
127.0.0.1 - - [18/Apr/2021 19:57:06] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Apr/2021 19:57:07] "GET /static/css/Hero.otf HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2021 19:57:07] "GET /static/css/BlurMedium.otf HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2021 19:57:08] "GET /begin HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2021 19:57:08] "GET /static/js/main.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2021 19:57:08] "GET /echo HTTP/1.1" 404 -
```

**Comment by avinashhsinghh** [comment]
This repository was not maintained from long time.

**Comment by kevincarrenot** [comment]
HELLO, CAN YOU HELP ME WITH THIS PROJECT...

**Comment by colinbrislawn** [comment]
I'm getting this type error.

```css
[2025-11-09 17:29:52 -0500] [3749] [INFO] Starting gunicorn 19.9.0                
[2025-11-09 17:29:52 -0500] [3749] [INFO] Listening at: http://127.0.0.1:8000 (3749)                                                                                
[2025-11-09 17:29:52 -0500] [3749] [INFO] Using worker: flask_sockets.worker      
[2025-11-09 17:29:52 -0500] [3756] [INFO] Booting worker with pid: 3756
Traceback (most recent call last):
  File "/home/biouser/miniconda3/envs/heartrate/lib/python3.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/home/biouser/miniconda3/envs/heartrate/lib/python3.7/site-packages/geventwebsocket/handler.py", line 75, in run_application
    self.run_websocket()
  File "/home/biouser/miniconda3/envs/heartrate/lib/python3.7/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
    list(self.application(self.environ, lambda s, h, e=None: []))
  File "/home/biouser/miniconda3/envs/heartrate/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/biouser/miniconda3/envs/heartrate/lib/python3.7/site-packages/flask_sockets.py", line 45, in __call__
    handler(environment, **values)
  File "/home/biouser/bin/github-repos/Heart-Rate-Detection/app.py", line 21, in echo_socket
    message = json.loads(ws.receive())
  File "/home/biouser/miniconda3/envs/heartrate/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
2025-11-09T22:30:19Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '39380', 'HTTP_HOST': '127.0.0.1:8000', (hidden keys: 31)} failed with TypeError
```

>This repository was not maintained from long time.

That's totally fair. Thank you for sharing your code!
